// This file is in the public domain.
#ifndef LIBJAMES_VERSION_H
#define LIBJAMES_VERSION_H

#define LIBJAMES_VERSION_MAJOR 1
#define LIBJAMES_VERSION_MINOR 0
#define LIBJAMES_VERSION_PATCH 0

#endif // LIBJAMES_VERSION_H
